name: node_http
description: HTTP client powered by Node.js I/O system.
version: 1.0.1
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.2.1
  node_interop: ^2.1.0
  node_io: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.8
  build_node_compilers:
    git:
      url: https://github.com/pulyaevskiy/node-interop.git
      path: build_node_compilers
      ref: fix-build-node-compilers
  build_test: ^2.2.2
  pedantic: ^1.0.0
  test: ^1.0.0
